
// Former Students
var formerstu = [
	["Dr. Jianzhao LIU","PhD. Student","none"],
	["Dr. Yong YU","PhD. Student","none"],
	["Dr. Cathy Ka Wai JIM","PhD. Student","none"],
	["Dr. Mahtab FAISAL","PhD. Student","none"],
	["Dr. Jie LI","PhD. Student","none"],
	["Dr. Affy Rongrong HU","PhD. Student","none"],
	["Dr. Carrie Yin Kwan CHAN","PhD. Student","none"],
	["Dr. Stella Yuning HONG","PhD. Student","none"],
	["Dr. Yilong CHEN","PhD. Student","none"],
	["Dr. Engui ZHAO","PhD. Student","none"],
	["Dr. Chris Wai Tung LEUNG","PhD. Student","none"],
	["Dr. Haiqin DENG","PhD. Student","none"],
	["Dr. Yajing LIU","PhD. Student","none"],
	["Dr. Zhegang SONG","PhD. Student","none"],
	["Dr. Yueyue ZHAO","PhD. Student","none"],
	["Dr. Yun ZHANG","PhD. Student","none"],
	["Dr. Chris Y.Y. Yu","PhD. Student","none"],
	["Mr. King Kei CHU", "MPh. Student","none"],
	["Mr. Jason Cheuk Yin NG", "MPh. Student","none"],
	["Dr. Pengcheng MA","PhD. Student","none"],
	["Mr. Ka Chun TSE", "MPh. Student","none"],
	["Dr. Matthias HAUBLER","PhD. Student","none"],
	["Dr. Lo Ming LAI","PhD. Student","none"],
	["Dr. Naveed Ahmed SIDDIQUI","PhD. Student","none"],
	["Dr. Zhiliang XIE","PhD. Student","none"],
	["Dr. Kevin Ka Leung CHEUK","PhD. Student","none"],
	["Dr. Kaitian XU","PhD. Student","none"],
	["Dr. Xiangxing KONG","PhD. Student","none"],
	["Mr. Charles Chi Wang LAW", "MPh. Student","none"],
	["Mr. Tommy Wan Hong POON", "MPh. Student","none"],
	["Miss Fennie Shu Mei LEUNG", "MPh. Student","none"],
	["Miss Priscilla Pui Sze LEE", "MPh. Student","none"],
	["Miss Many Wun Man JEU","MSc. Student","none"],
	["Miss Kawai CHIU","MSc. Student","none"],
	["Mr. Joseph Wai Hou LEUNG","MSc. Student","none"],
	["Mr. Norman Hoi Ching MONG","MSc. Student","none"],
	["Mr. Richard Wai Choi LUK","MSc. Student","none"]
];

// Former postdoc
var formpost = [
	["Prof. Anjun QIN","Postdoc Fellow","none"],
	["Prof. Yuping DONG","Postdoc Fellow","none"],
	["Dr. Ping LU","Postdoc Fellow","none"],
	["Dr. Wangzhang YUAN","Postdoc Fellow","none"],
	["Dr. Zujin ZHAO","Postdoc Fellow","none"],
	["Dr. Yang LIU","Postdoc Fellow","none"],
	["Dr. Nai Wen TSENG","Postdoc Fellow","none"],
	["Dr. Chunmei DENG","Postdoc Fellow","none"],
	["Dr. Liping HENG","Postdoc Fellow","none"],
	["Dr. Xianmin GAO","Postdoc Fellow","none"],
	["Dr. Qin HU","Postdoc Fellow","none"],
	["Dr. Zhengke WANG","Postdoc Fellow","none"],
	["Dr. Meng GAO","Postdoc Fellow","none"],
	["Dr. Shuhong LI","Postdoc Fellow","none"],
	["Dr. Zhiyong YANG","Postdoc Fellow","none"],
	["Dr. Na ZHAO","Postdoc Fellow","none"],
	["Dr. Xiaoding LOU","Postdoc Fellow","none"],
	["Dr. Min LI","Postdoc Fellow","none"],
	["Dr. Dongyu ZHAO","Postdoc Fellow","none"],
	["Dr. Qiuhua ZHU","Postdoc Fellow","none"],
	["Dr. Mathieu ARSENEAULT","Postdoc Fellow","none"],
	["Dr. Erjing Wang","Postdoc Fellow","none"],
	["Dr. Hongkun Li","Postdoc Fellow","none"],
	["Dr. Ju Mei","Postdoc Fellow","none"],
	["Dr. Zikai HE","Postdoc Fellow","none"],
	["Dr. Yuanjing CAI","Postdoc Fellow","none"],
	["Dr. Jessie Roose","Postdoc Fellow","none"],
	["Mr. Yu MAO","Research Assistant","none"],
	["Mr. Jian WANG","Research Assistant","none"],
	["Mr. Jiming YAN","Research Assistant","none"],
	["Mr. Xiaoyuan SHEN","Research Assistant","none"],
	["Mr. Qiang WEI","Research Assistant","none"],
	["Mr. Yi LIU","Research Assistant","none"],
	["Miss Li TONG","Research Assistant","none"],
	["Miss Qiuli ZHAO","Research Assistant","none"],
	["Mr. Jiaqi TONG","Research Assistant","none"],
	["Mr. Haiqiang WU","Research Assistant","none"],
	["Mr. Zhe WANG","Research Assistant","none"],
	["Mr. Tao JIANG","Research Assistant","none"],
	["Mr. Toshifumi INOUCHI","Research Assistant","none"],
	["Mr. Bicheng YAO","Research Assistant","none"],
	["Mr. Yunbo CAI","Research Assistant","none"],
	["Mr. Yuan GAO","Research Assistant","none"],
	["Mr. Kai LI","Research Assistant","none"],
	["Mr. Tianyu HAN","Research Assistant","none"],
	["Mr. Haoke ZHANG","Research Assistant","none"],
	["Mr. Long CHEN","Research Assistant","none"],
	["Mr. Yongwei WU","Research Assistant","none"],
	["Mr. Han NIE","Research Assistant","none"],
	["Mr. Kun HU","Research Assistant","none"],
	["Miss. Yijia WANG","Research Assistant","none"],
	["Miss Lingzhi LI","Research Assistant","none"],
	["Mr. Zongtan WANG","Research Assistant","none"],
	["Mr. Ming CHEN","Research Assistant","none"],
	["Mr. Xiao WANG","Research Assistant","none"],
	["Mr. Bo SITU","Research Assistant","none"],
	["Mr. Meng HE","Research Assistant","none"],
	["Mr. Zhenfeng ZHU","Research Assistant","none"],
	["Mr. Yiliu LIN","Research Assistant","none"],
	["Mr. Dongdong LI","Research Assistant","none"],
	["Mr. Yizhao CHAN","Research Assistant","none"],
	["Mr. Chao ZHENG","Research Assistant","none"],
	["Mr. Qiang WANG","Student","none"],
	["Mr. XiaoA ZHANG","Student","none"],
	["Mr. Hongkun LI","Student","none"],
	["Miss Xiujuan CHEN","Student","none"],
	["Prof. Yiwang CHEN","Student","none"],
	["Miss Limin XU","Student","none"],
	["Miss Dinara BIRIMZHANOVA","Student","none"],
	["Mr. Changyi LI","Student","none"],
	["Mr. Sohail NOOR","Student","none"],
	["Prof. Eduardo PENA-CABRERA","Student","none"],
	["Mr. Hui ZHAO","Student","none"],
	["Miss Li TANG","Student","none"],
	["Dr. Jianbing SHI","Student","none"],
	["Prof. Minxin YE","Student","none"],
	["Mr. Fan HU","Student","none"],
	["Dr. Zhen LI","Student","none"],
	["Dr. Changmin XING","Student","none"],
	["D r. Yongqiang DONG","Student","none"],
	["Mr. Haipeng XU","Student","none"],
	["Ms. Han PENG","Student","none"],
	["Dr. Lumei LIU","Student","none"],
	["Dr. Jianli HUA","Student","none"],
	["Dr. Baoxiu MI","Student","none"],
	["Miss Tian HUANG","Student","none"],
	["Dr. Hui TONG","Student","none"],
	["Mr. Penglin YE","Student","none"],
	["Dr. Ronghua ZHENG","Student","none"],
	["Dr. Junwu CHEN","Student","none"],
	["Mr. Charles C. W. LAW","Student","none"],
	["Dr. Lin CHENG","Student","none"],
	["Ms. Han PENG","Student","none"],
	["Ms. Bingshi LI","Student","none"],
	["Dr. Jingdong LUO","Student","none"],
	["Dr. Xiaowei ZHAN","Student","none"],
	["Dr. Fouad SALHI","Student","none"],
	["Dr. Gao LI","Student","none"],
	["Dr. Hongzheng CHEN","Student","none"],
	["Dr. Qunhui SUN","Student","none"],
	["Dr. Xiangxing KONG","Student","none"],
	["Dr. Yanhuo GENG","Student","none"],
	["Dr. Hongyao XU","Student","none"],
	["Mr. Bensheng LI","Student","none"],
	["Prof. Huilin CHEN","Student","none"],
	["Dr. Xinhua WAN","Student","none"],
	["Dr. Weili LI","Student","none"]
];


var rfs = [];
formerstu.forEach(x => rfs.push(generateHTML(x, 'category04', 'base')));
formerpost.forEach(x => rfs.push(generateHTML(x, 'category05' , 'base')));
document.body.innerText = rfs.join('\n');